### ISSUE TITLE
Build nav interaction/transition from hero

### ISSUE THREAD

**Issue by glynnis** [siakaramalegos/clioandcalliope#17]
Build a navigation interaction that keeps the navigation on screen even when a user scrolls down past the hero image on the homepage. 

* This may also include work on the nav functionality for other content pages.
* This should also include any transitions needed for small screen sizes (hamburger menu)

This may be a helpful article on how to achieve such a menu using only CSS: https://scotch.io/tutorials/building-a-morphing-hamburger-menu-with-css

**Comment by siakaramalegos** [comment]
Also needs to include a style modification for the current link (like if on About page or in Specialties section)

**Comment by siakaramalegos** [comment]
See also this for sticky nav with vanilla js https://www.w3schools.com/howto/howto_js_navbar_sticky.asp
