### ISSUE TITLE
Add meta tags for SEO

### ISSUE THREAD

**Issue by siakaramalegos** [siakaramalegos/clioandcalliope#23]
Description and share image

**Comment by siakaramalegos** [comment]
@glynnis  can you provide the image? I'll need to set up how Webpack treats it so just put in our marketing image folder and let me know...

i'm thinking something like the hero - with our name and tag line on the door background but i'm definitely open to your ideas too! we could vary on each page but maybe not so important as just getting one good one.

From facebook docs:
https://developers.facebook.com/docs/sharing/best-practices
Image Sizes
Use images that are at least 1200 x 630 pixels for the best display on high resolution devices. At the minimum, you should use images that are 600 x 315 pixels to display link page posts with larger images. Images can be up to 8MB in size.

**Comment by glynnis** [comment]
I've added it to the marketing folder -- "share_image.jpg".
