### ISSUE TITLE
Build home page

### ISSUE THREAD

**Issue by siakaramalegos** [siakaramalegos/clioandcalliope#7]
Finish up index page

**Comment by glynnis** [comment]
For implementing the "Specialties" section with the gradient background, the way InVision generated CSS properties from the layers I had to create for the chevron shape probably won't be the cleanest way to handle it.

Basically: as long as we figure out a good way to handle the gradient in code, I don't expect it to exactly match what's on InVision.

Food for thought/in case it's helpful: 
* Basic gradients with some fallbacks: https://codepen.io/pirrera/pen/lwIpx - `lbg2` is pretty close to our colors if we just swap out the blue for `#00A6BF`, though `lbg6` is a bit closer in terms of radial direction
* Using multiple gradients on a single element - https://stackoverflow.com/questions/10677429/how-to-apply-multiple-css-radial-gradients-to-a-single-element
* A cool animated gradient if we want to get fancy: https://codepen.io/zacharyhickson/pen/efaik

**Comment by glynnis** [comment]
Latest is up on InVision -- see #10

**Comment by glynnis** [comment]
This looks pretty close actually (including vendor pre-fixes just in case, but I haven't checked caniuse.com to see if we really need all of them):
```
background-image: -webkit-gradient(linear, 0% 100%, 100% 0%, color-stop(0%, #0aa8be), color-stop(100%, #2bbbae));
background-image: -webkit-linear-gradient(left bottom, #0aa8be 0%, #2bbbae 100%);
background-image: linear-gradient(to right top, #0686ad 0%, #2bbbae 100%);
```

**Comment by siakaramalegos** [comment]
Needs responsive tweaks.
